<?php
/******************************************************************************
 * Archivo: mapica.phtml
 * Contenido: Página principal de la publicación web del SIG de flora.
 * Autor: Óscar El Becario Eterno.
 * Versión: 0.0.8 (Preludio Alfalfa) - 18/12/2014
 * Descripción: Archivo de texto plano precioso y encantador con código PHP
 * para generar la página web que muestre el mapa de flora, así como ir
 * actualizando dicha web en base a las capas seleccionadas, opciones y
 * demás interacciones.
 * 
 * Notas: Nada a desastacar... por ahora. Todas las cañerías en orden.
 *
 ******************************************************************************/
// Prevención (sólo eso) de vulnerabilidad de seguridad XSS (Secuencias de comandos en sitios cruzados)
if(isset($_REQUEST['PM_INCPHP'])){
	exit();
}

// Establecer ruta de "cookies" separada para cada instancia de "p.mapper" para evitar sesiones en conflicto cuando "session.use_cookies" sea "true" (cierto)
if(ini_get("session.use_cookies")){
	ini_set("session.cookie_path", dirname($_SERVER['SCRIPT_NAME']));
}

require_once("incphp/pmsession.php");

// Inclusión de archivos ".php" y establecimiento de parámetros varios
require_once("config/__startup_config.php");
require_once("incphp/group.php");
$_SESSION['mapObjModifierFirstInclude'] = true;
require_once("incphp/globals.php");
$_SESSION['mapObjModifierFirstInclude'] = false;
require_once("incphp/common.php");
require_once("incphp/init/initmap.php");
require_once("incphp/legend.php");
include_once("incphp/init/init.php");
include_once("incphp/uielement.php");

// Directiva de PHP para que se muestre en la codificación definida
header("Content-type: text/html; charset=$defCharset");

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $gLanguage ?>" xml:lang="<?php echo $gLanguage ?>">

<head>
 <meta http-equiv="Content-Script-Type" content="text/javascript" />
 <meta name="description" content="SIG de flora de Motril" />
 <meta name="author" content="Óscar El Becario Eterno" />
 <meta name="keywords" content="Motril, flora, parques, jardines, plantas, árboles, matas, matojos" />
 
 <title><?php echo $_SESSION['pmTitle'] ?></title>
 
 <!--<script src="javascript/src/jquery/jquery-1.5.1.min.js"></script>
 <script src="javascript/src/optional/ui/jquery.layout.min.js"></script>
 <script src="javascript/src/optional/ui/jquery-ui-1.8.4.custom.min.js"></script>-->
 
  <?php 
   
   // Cargar todos los archivos ".js" de los directorios 'javascript' y 'config'
   echo $jsReference; 
   
   echo $jsConfigReference;
   
   echo $jsCustomReference;
   
   // Reference all global JS variables
   include("incphp/js/js_init.php"); 
  ?>

 <!--<script src="javascript/src/optional/ui/jquery-ui-1.8.4.custom.min.js"></script>
 <script src="javascript/src/optional/ui/jquery.layout.min.js"></script>-->
 <!--<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>-->
<!--<script src="javascript/src/pm.zoombox.js"></script>-->
 
 <link rel="shortcut icon" href="images/Escudo_Azul_Motril_peque.ico" type="image/x-icon" />
 <link rel="stylesheet" href="templates/default.css" type="text/css" />
 <link rel="stylesheet" href="templates/layout.css" type="text/css" />
 <link rel="stylesheet" href="templates/tuneo/layout.tuneado.css" type="text/css" />
 <link rel="stylesheet" href="templates/jquery.treeview.css" type="text/css" />
 <link rel="stylesheet" href="templates/toc.css" type="text/css" />
 <link rel="stylesheet" href="templates/query.css" type="text/css" />
 <link rel="stylesheet" href="templates/dialog.css" type="text/css" />
 <link rel="stylesheet" href="templates/jquery.layout.css" type="text/css" />
  <link rel="stylesheet" href="templates/tuneo/custom.css" type="text/css" />
 <!--[if lt IE 7]> 
 <link rel="stylesheet" href="templates/ie6.css" type="text/css" />
 <![endif]--> 
 
 <!--<script src="javascript/jquery-ui-1.11.2.custom/jquery-ui.js" type="text/javascript" />-->
 
 <style type="text/css">
 <!--
   /*.ui-layout-east {border: 1px solid #999999; background-color:#e9e9e9;}
   .ui-layout-center {border: 1px solid #999999;}
   .ui-layout-root {border: 1px solid #000000;}*/
 }
 -->
 </style>

 
 <?php 
    // Load all CSS files from config directory
    echo $cssReference; 
 ?>
 
 	<script type="text/javascript">

	
    $.extend(PM.Layout,
    {
        /**
         * Resize UI containers after root element resize
         */
        resizeContainers: function() {
            //var rootElem = $(window);
            var rootElem = $('#uiLayoutRoot'); 
            var rootH = rootElem.height();
            var rootW = rootElem.width();
            var northH = $('#uiLayoutNorth').outerHeight({margin:false, border:false});
            var southH = $('#uiLayoutSouth').outerHeight({margin:false});
            var mH = rootH - northH - southH;
            
            $('#uiLayoutCenter').css({position:'absolute', height:'100%'})
                                //.height(mH)
                                .width(rootW - $('#uiLayoutWest').outerWidth({margin:false}) - $('#uiLayoutEast').outerWidth({margin:false}))
                                //.top(northH)
								.top(0)
                                //.left($('#uiLayoutWest').outerWidth({margin:false}));
								.left($('#uiLayoutWest').width());
            $('#uiLayoutEast').height(mH).top(northH);
            $('#toc, #toclegend').height(mH - $('#refmap').height() - $('#toc').itop() - 8);
                                
            PM.Layout.resizeMapZone();
        }
        
    });
    
    
	/**
     * Settings for jquery.ui.layout
     * ======= ADAPT TO PAGE LAYOUT =======
     */
	$(document).ready(function () {
	
/**************************/	
        var mrgH = 6;
        var mrgV = 6;
		var lcW = 250;
        var barH = 32;
        //$('#uiLayoutRoot').css({position:'absolute',  top:10, bottom:10, left:10, right:10});
		$('#uiLayoutRoot').css({position:'absolute', top:0, bottom:0, left:0, right:0});
        /*
		$('#uiLayoutWest').css({position:'absolute', width:0, 'margin-right':mrgH});
        $('#uiLayoutEast').css({position:'absolute', right:0, width:240, height:'100%', 'margin-left':mrgH, 'margin-right':mrgH, 'z-index':99});
		*/
		$('#uiLayoutEast').css({position:'absolute', width:0});
        $('#uiLayoutWest').css({position:'absolute', left:0, width:lcW, height:'100%', 'margin-right':0});
        //$('#uiLayoutNorth').css({position:'absolute', top:0, height:40, width:'100%', 'margin-bottom':mrgV});
		$('#uiLayoutNorth').css({position:'absolute', top:0, height:0});
        //$('#uiLayoutSouth').css({position:'absolute', bottom:0, height:35, width:'100%', 'margin-top':mrgV+2});
		$('#uiLayoutSouth').css({position:'absolute', bottom:0, height:0});
        
        /** Some components to be added to UI */
        $('#uiLayoutCenter').pmToolBar(PM.botonesTuneados);  // ToolBar, REQUIRED
        //$('#uiLayoutNorth').pmToolLinks(PM.linksDefault);   // Tool links
        //$('#uiLayoutCenter').appendElement('div').addClass('map-top-bar');  // Top bar over map
        
		MostrarOcultarHerramientas();
		
        PM.Layout.resizeContainers();
        $(window).resize(function(){
            PM.Layout.resizeContainers();
        });
 	});

    
	</script>

	<script>
	// Acordeones para tocar música de la güena mientras la cabra sube y baja la escalera
	// Añadir tooltip para abrir cerrar, entre otros
	/*$(function() {
		var iconos_abrir_cerrar = {
			header: "ui-icon-circle-arrow-e",
			activeHeader: "ui-icon-circle-arrow-s"
		};
		$( "#toolBar" ).accordion({
			icons: iconos_abrir_cerrar,
			collapsible: true
		});
	});*/
	function OcultarPanelLateral() {
		//Ocultar panel lateral y redimensionar mapa
		$('#uiLayoutWest').css({width:0});
		PM.Layout.resizeContainers();
		//Mostar botón para remostrar panel
		$('#mostrar-panel-lateral').css({visibility:'visible'});
	}
	
	function MostrarPanelLateral() {
		//Ocultar botón para remostrar panel
		$('#mostrar-panel-lateral').css({visibility:'hidden'});
		//Mostar panel lateral y redimensionar mapa
		$('#uiLayoutWest').css({width:250});
		PM.Layout.resizeContainers();
	}
	
	function MostrarOcultarHerramientas() {
		//Cambiar texto del botón
		if(PM.barraHerramientasOculta) {
			$('#mostrar-barra-herrammientas').attr({title: 'Mostrar barra de herrammientas'});
			$('#mostrar-barra-herrammientas > img').attr({alt: 'Mostrar'});
			$('#toolBar').css({visibility:'hidden'});
		}
		else {
			$('#mostrar-barra-herrammientas').attr({title: 'Ocultar barra de herrammientas'});
			$('#mostrar-barra-herrammientas > img').attr({alt: 'Ocultar'});
			$('#toolBar').css({visibility:'visible'});
		}
		//Cambiar valor para la visibilidad
		PM.barraHerramientasOculta = !PM.barraHerramientasOculta;
	}
	
	function MostrarAcercaDe() {
		var ADparametros = {
			width: 640,
			height: 240,
			left: 100,
			top: 50,
			resizeable: false,
			newsize: true,
			container: 'acercade',
			name: 'AcercaDe'
		};
		var ADdireccion = "acercadlg.phtml?" + SID;
		var ADObjeto = $('#' + ADparametros.container + '_MSG');
		
		if (ADObjeto.length < 1) {
			var dlg = PM.Dlg.createDnRDlg(ADparametros, _p('Acerca de'), ADdireccion);
		}
		else {
			$.ajax({
				url: ADdireccion,
				type: 'GET',
				dataType: 'html',
				success: function(response) {
					ADObjeto.html(response);
					ADObjeto.parent().parent().show();
				}
			});
		}
	}

	</script>
	
</head>

<body>

<!-- ======================= ADAPT START ======================== -->
<div class="ui-layout-root" id="uiLayoutRoot" >
	
	<div class="ui-layout-north" id="uiLayoutNorth"></div>
	
	<div class="ui-layout-east" id="uiLayoutEast"></div>
	
	<div class="ui-layout-south" id="uiLayoutSouth"></div>
	
	<div class="ui-layout-west" id="uiLayoutWest">
		<!-- Header -->
        <?php /*echo UiElement::pmHeader()*/
		echo UiElement::PL_Cabecera();
		?>
        
        <!-- Legend/TOC -->
        <?php echo UiElement::PL_Leyenda($_SESSION['userAgent']) ?>
            
		<!-- <div id="legend"></div> -->
        <!-- Reference Map -->
        <?php /* echo UiElement::refMap($refH, $refW, $refImg, $refH, $refW) */?>
	</div>
	
	<div class="ui-layout-center" id="uiLayoutCenter">
        <!-- Map Zone -->
        <?php echo UiElement::mapZone() ?>
        
        <!-- Slider -->
        <?php echo UiElement::zoomSlider() ?>
        
        <!-- Search Container -->
        <?php echo UiElement::searchContainer("block") ?>
        
        <!-- Tools Button -->
        <?php echo UiElement::PC_MostrarBarraHerramientas()?>
        
        <!-- Scale -->
        <?php echo UiElement::scaleForm() ?>
		
		<!-- Coordinates -->
		<?php echo UiElement::displayCoordinates() ?>
		
		<!-- Footer -->
        <?php /*echo UiElement::pmFooter()*/
		echo UiElement::PC_Pie()
		?>
		
		<?php /*echo UiElement::pmFooter()*/
		echo UiElement::PC_LogoLBSL()
		?>
		
		<!-- Mostrar/Ocultar panel izquierdo -->
		<?php  echo UiElement::PC_MostrarPanelLateral() ?>
        
	</div>

<!-- ======================= ADAPT END ======================== -->
</div>

<div style="visibility:hidden"><img id="pmMapRefreshImg" src="images/pixel.gif" alt="" /></div>
<div style="visibility:hidden"><img src="images/pixel.gif" alt="" /></div>

<!-- MANDATORY form element for update events; DO NOT REMOVE! -->
<?php echo UiElement::addUpdateEventForm()?>

<script type="text/javascript">
    // use jQuery for intitialization 
    $(document).ready(function() {
        PM.Init.main();
        <?php echo $jsInitFunctions ?>
    });
    
    // Create drawing object for measure function
    jg = new jsGraphics('measureLayer');
    jg.setColor(PM.measureObjects.line.color); 
    jg.setStroke(PM.measureObjects.line.width);
    
    //#fede
    jg_tmp = new jsGraphics('measureLayerTmp');
    
</script>

</body>
</html>